CREATE TABLE article
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    content   VARCHAR(255)                            NOT NULL,
    author_id BIGINT,
    CONSTRAINT pk_article PRIMARY KEY (id)
);

ALTER TABLE article
    ADD CONSTRAINT FK_ARTICLE_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE article
    ADD COLUMN category_id BIGINT;
ALTER TABLE article
    ADD CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES article_categories(id);