CREATE TABLE article_categories
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_article_categories PRIMARY KEY (id)
);

ALTER TABLE article_categories
    ADD CONSTRAINT uc_article_categories_name UNIQUE (name);