CREATE TABLE chords
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(20)                             NOT NULL,
    diagram_url VARCHAR(255)                            NOT NULL,
    difficulty  VARCHAR(10),
    CONSTRAINT pk_chords PRIMARY KEY (id)
);