CREATE TABLE guitar_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(50)                             NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_guitar_types PRIMARY KEY (id)
);

ALTER TABLE guitar_types
    ADD CONSTRAINT uc_guitar_types_name UNIQUE (name);